#!/usr/bin/env bash

if [[ `uname -r` == *"ARCH" ]]; then
	sudo pacman -S --needed --noconfirm vim
	sudo pacman -S --needed --noconfirm ctags
elif [ -e "/etc/fedora-release" ]; then
	sudo dnf install -y vim
	sudo dnf install -y ctags
fi


 # Install latest VIM Pathogen
#mkdir -p ~/.vim/autoload ~/.vim/bundle/start
#curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

mkdir -p ~/.vim/pack/plugins/start

# install lastest VIM Syntastic
rm -rf ~/.vim/pack/plugins/start/syntastic 2> /dev/null
git clone https://github.com/scrooloose/syntastic.git ~/.vim/pack/plugins/start/syntastic

# Install lastest VIM Sensible
rm -rf  ~/.vim/pack/plugins/start/vim-sensible 2> /dev/null
git clone git://github.com/tpope/vim-sensible.git ~/.vim/pack/plugins/start/vim-sensible

# Install lastest VIM tagbar (package ctags needs to be installed previously)
rm -rf  ~/.vim/pack/plugins/start/tagbar 2> /dev/null
git clone https://github.com/majutsushi/tagbar ~/.vim/pack/plugins/start/tagbar

# Install lastest VIM NERDTree
rm -rf  ~/.vim/pack/plugins/start/nerdtree 2> /dev/null
git clone https://github.com/scrooloose/nerdtree ~/.vim/pack/plugins/start/nerdtree

# Install lastest VIM lightline
rm -rf  ~/.vim/pack/plugins/start/lightline 2> /dev/null
git clone https://github.com/itchyny/lightline.vim ~/.vim/pack/plugins/start/lightline

# Install lastest VIM neocomplete
rm -rf  ~/.vim/pack/plugins/start/neocomplete 2> /dev/null
git clone https://github.com/Shougo/neocomplete.vim.git ~/.vim/pack/plugins/start/neocomplete

# Install lastest VIM ultiSnips
#rm -rf  ~/.vim/pack/plugins/start/ultisnips 2> /dev/null
#git clone https://github.com/SirVer/ultisnips.git ~/.vim/pack/plugins/start/ultisnips

# Install lastest VIM vim-choosewin
rm -rf  ~/.vim/pack/plugins/start/vim-choosewin 2> /dev/null
git clone https://github.com/t9md/vim-choosewin.git ~/.vim/pack/plugins/start/vim-choosewin

# Install VIM crlp.vim (used by vim-go)
#rm -rf  ~/.vim/pack/plugins/start/ctrlp.vim 2> /dev/null
#git clone https://github.com/ctrlpvim/ctrlp.vim.git ~/.vim/pack/plugins/start/ctrlp.vim

# Install lastest VIM splitjoin
rm -rf  ~/.vim/pack/plugins/start/splitjoin 2> /dev/null
git clone git://github.com/AndrewRadev/splitjoin.vim.git ~/.vim/pack/plugins/start/splitjoin

# Install VIM Conque-Term
#vim 'https://conque.googlecode.com/files/conque_2.3.vmb' -c ':so % | q'

# Install lastest VIM vim-go
if [ -d "/usr/local/go" ]; then
	rm -rf  ~/.vim/pack/plugins/start/vim-go 2> /dev/null
	git clone https://github.com/fatih/vim-go.git ~/.vim/pack/plugins/start/vim-go
	vim +GoInstallBinaries
fi


# Rebuild the help tag files for the pluggins
#vim -c "Helptags" -c "qa"
vim +Helptags

# Cleanup
rm ~/.dotfiles/vim/vim 2> /dev/null
